### ISSUE TITLE
Url is broken?

### ISSUE THREAD

**Issue by mxshaun** [osjoberg/Carwings#1]
Exception I get after trying to Login. 
Both when using CarwingsService and Carwings.ApiClient

Unexpected HTTP response. HTTP Status Code: 404, Response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api_v190426_NE/gdc/InitialApp_v2.php was not found on this server.</p>
</body></html>
.

**Comment by osjoberg** [comment]
Yes, the base URL has been changed - it is not simply only to replace the base URL, there are API changes as well. Will try to fix this during December.

**Comment by osjoberg** [comment]
Should be fixed now.
